### ISSUE TITLE
FileNotFoundException for filenames with accented characters. 

### ISSUE THREAD

**Issue by 0xbadidea** [databricks-industry-solutions/hls-interop-workshop-jan23#1]
Get the below error complaining about missing files, when the fine names contain special characters. What's the best way around this issue?

```
spark.conf.set("spark.sql.caseSensitive", "true")
df = (
  spark.read.format('xml')
   .option("rowTag", "ClinicalDocument")
  .load('/user/hive/warehouse/hls_cms_source.db/raw_files/synthea_mass/ccda/')
)
```

```org.apache.spark.SparkException: Job aborted due to stage failure: Task 43 in stage 251.0 failed 4 times, most recent failure: Lost task 43.3 in stage 251.0 (TID 494) (10.139.64.6 executor 0): java.io.FileNotFoundException: /4842022074360943/user/hive/warehouse/hls_cms_source.db/raw_files/synthea_mass/ccda/Amalia471_Magaña874_3912696a-0aef-492e-83ef-468262b82966.xml```

Edit: I'm using DBR 10.4 LTS (includes Apache Spark 3.2.1, Scala 2.12)

**Comment by zavoraad** [comment]
Hi @0xbadidea,

I'm wondering if removing the prefix "dbfs" from the path changes the file location from a distributed file system to local file system and potentially changes behavior depending on what compute resources were created?

**Comment by 0xbadidea** [comment]
I imported the notebook as is and re-ran the same command on the Databricks cluster and got the same result.
```spark.conf.set("spark.sql.caseSensitive", "true")
df = (
  spark.read.format('xml')
   .option("rowTag", "ClinicalDocument")
  .load("dbfs:/user/hive/warehouse/hls_cms_source.db/raw_files/synthea_mass/ccda/")
)

df.write.format("parquet").mode("overwrite").saveAsTable("hls_synthetic_claims.ccda_claims_synthea_mass")
```

This code still results in the below error:
```
org.apache.spark.SparkException: Job aborted due to stage failure: Task 43 in stage 1.0 failed 4 times, most recent failure: Lost task 43.3 in stage 1.0 (TID 103) (10.139.64.4 executor 1): java.io.FileNotFoundException: /4842022074360943/user/hive/warehouse/hls_cms_source.db/raw_files/synthea_mass/ccda/Amalia471_Magaña874_3912696a-0aef-492e-83ef-468262b82966.xml
```

Everything works just fine when I remove the files with accented characters in the filename. I wonder why?

**Comment by zavoraad** [comment]
Interesting, I wonder if it's related to how file names are translated to Spark on a given cloud or maybe specific setup on that cloud? I ran the demo on AWS. 

For a quick renaming workaround, here is a scala block in Databricks notebook you can run to automatically rename any files to remove special characters

```scala
%scala
//Filter files with special characters 
val files = dbutils.fs.ls("dbfs:/user/hive/warehouse/hls_cms_source.db/raw_files/synthea_mass/ccda/").filter(file => ! file.name.getBytes.filter(x => x < 0).isEmpty ) 
//Rename these files without special characters
files.foreach(file => dbutils.fs.mv(file.path, file.path.getBytes.filter(x => x > 0).map(_.toChar).mkString))
 ```

**Comment by 0xbadidea** [comment]
Even the workaround results in the below errror. Not sure, `if it has something to do with the Azure environment, I'm on. 

``
`FileNotFoundException: dbfs:/user/hive/warehouse/hls_cms_source.db/raw_files/synthea_mass/ccda/Amalia471_Magaña874_3912696a-0aef-492e-83ef-468262b82966.xml`

at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.$anonfun$getFileStatus$2(DatabricksFileSystemV2.scala:872)
	at com.databricks.s3a.S3AExceptionUtils$.convertAWSExceptionToJavaIOException(DatabricksStreamUtils.scala:70)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.$anonfun$getFileStatus$1(DatabricksFileSystemV2.scala:858)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperation$1(UsageLogging.scala:330)
	at com.databricks.logging.UsageLogging.executeThunkAndCaptureResultTags$1(UsageLogging.scala:424)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$4(UsageLogging.scala:444)
	at com.databricks.logging.Log4jUsageLoggingShim$.$anonfun$withAttributionContext$1(Log4jUsageLoggingShim.scala:33)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:94)
	at com.databricks.logging.Log4jUsageLoggingShim$.withAttributionContext(Log4jUsageLoggingShim.scala:31)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:205)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:204)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.withAttributionContext(DatabricksFileSystemV2.scala:510)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:240)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:225)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.withAttributionTags(DatabricksFileSystemV2.scala:510)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags(UsageLogging.scala:419)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags$(UsageLogging.scala:339)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.recordOperationWithResultTags(DatabricksFileSystemV2.scala:510)
	at com.databricks.logging.UsageLogging.recordOperation(UsageLogging.scala:330)
	at com.databricks.logging.UsageLogging.recordOperation$(UsageLogging.scala:302)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.recordOperation(DatabricksFileSystemV2.scala:510)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystemV2.getFileStatus(DatabricksFileSystemV2.scala:858)
	at com.databricks.backend.daemon.data.client.DatabricksFileSystem.getFileStatus(DatabricksFileSystem.scala:215)
	at com.databricks.backend.daemon.dbutils.FSUtils$.$anonfun$withMvSafetyChecks$2(DBUtilsCore.scala:127)
	at com.databricks.backend.daemon.dbutils.FSUtils$.withFsSafetyCheck(DBUtilsCore.scala:91)
	at com.databricks.backend.daemon.dbutils.FSUtils$.$anonfun$withMvSafetyChecks$1(DBUtilsCore.scala:123)
	at com.databricks.backend.daemon.dbutils.FSUtils$.withFsSafetyCheck(DBUtilsCore.scala:91)
	at com.databricks.backend.daemon.dbutils.FSUtils$.withMvSafetyChecks(DBUtilsCore.scala:123)
	at com.databricks.backend.daemon.dbutils.FSUtils$.mv(DBUtilsCore.scala:199)
	at com.databricks.dbutils_v1.impl.DbfsUtilsImpl.$anonfun$mv$1(DbfsUtilsImpl.scala:143)
	at scala.runtime.java8.JFunction0$mcZ$sp.apply(JFunction0$mcZ$sp.java:23)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperation$1(UsageLogging.scala:330)
	at com.databricks.logging.UsageLogging.executeThunkAndCaptureResultTags$1(UsageLogging.scala:424)
	at com.databricks.logging.UsageLogging.$anonfun$recordOperationWithResultTags$4(UsageLogging.scala:444)
	at com.databricks.logging.Log4jUsageLoggingShim$.$anonfun$withAttributionContext$1(Log4jUsageLoggingShim.scala:33)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:94)
	at com.databricks.logging.Log4jUsageLoggingShim$.withAttributionContext(Log4jUsageLoggingShim.scala:31)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:205)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:204)
	at com.databricks.dbutils_v1.impl.DbfsUtilsImpl.withAttributionContext(DbfsUtilsImpl.scala:20)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:240)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:225)
	at com.databricks.dbutils_v1.impl.DbfsUtilsImpl.withAttributionTags(DbfsUtilsImpl.scala:20)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags(UsageLogging.scala:419)
	at com.databricks.logging.UsageLogging.recordOperationWithResultTags$(UsageLogging.scala:339)
	at com.databricks.dbutils_v1.impl.DbfsUtilsImpl.recordOperationWithResultTags(DbfsUtilsImpl.scala:20)
	at com.databricks.logging.UsageLogging.recordOperation(UsageLogging.scala:330)
	at com.databricks.logging.UsageLogging.recordOperation$(UsageLogging.scala:302)
	at com.databricks.dbutils_v1.impl.DbfsUtilsImpl.recordOperation(DbfsUtilsImpl.scala:20)
	at com.databricks.dbutils_v1.impl.DbfsUtilsImpl.recordDbutilsFsOp(DbfsUtilsImpl.scala:81)
	at com.databricks.dbutils_v1.impl.DbfsUtilsImpl.mv(DbfsUtilsImpl.scala:140)
	at $lineb4ae9064c7a245fcbbd67be34e2b669725.$read$$iw$$iw$$iw$$iw$$iw$$iw.$anonfun$res0$1(command-1493318147779329:4)
	at $lineb4ae9064c7a245fcbbd67be34e2b669725.$read$$iw$$iw$$iw$$iw$$iw$$iw.$anonfun$res0$1$adapted(command-1493318147779329:4)
	at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:36)
	at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:33)
	at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:38)
	at $lineb4ae9064c7a245fcbbd67be34e2b669725.$read$$iw$$iw$$iw$$iw$$iw$$iw.<init>(command-1493318147779329:4)
	at $lineb4ae9064c7a245fcbbd67be34e2b669725.$read$$iw$$iw$$iw$$iw$$iw.<init>(command-1493318147779329:47)
	at $lineb4ae9064c7a245fcbbd67be34e2b669725.$read$$iw$$iw$$iw$$iw.<init>(command-1493318147779329:49)
	at $lineb4ae9064c7a245fcbbd67be34e2b669725.$read$$iw$$iw$$iw.<init>(command-1493318147779329:51)
	at $lineb4ae9064c7a245fcbbd67be34e2b669725.$read$$iw$$iw.<init>(command-1493318147779329:53)
	at $lineb4ae9064c7a245fcbbd67be34e2b669725.$read$$iw.<init>(command-1493318147779329:55)
	at $lineb4ae9064c7a245fcbbd67be34e2b669725.$read.<init>(command-1493318147779329:57)
	at $lineb4ae9064c7a245fcbbd67be34e2b669725.$read$.<init>(command-1493318147779329:61)
	at $lineb4ae9064c7a245fcbbd67be34e2b669725.$read$.<clinit>(command-1493318147779329)
	at $lineb4ae9064c7a245fcbbd67be34e2b669725.$eval$.$print$lzycompute(<notebook>:7)
	at $lineb4ae9064c7a245fcbbd67be34e2b669725.$eval$.$print(<notebook>:6)
	at $lineb4ae9064c7a245fcbbd67be34e2b669725.$eval.$print(<notebook>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at scala.tools.nsc.interpreter.IMain$ReadEvalPrint.call(IMain.scala:747)
	at scala.tools.nsc.interpreter.IMain$Request.loadAndRun(IMain.scala:1020)
	at scala.tools.nsc.interpreter.IMain.$anonfun$interpret$1(IMain.scala:568)
	at scala.reflect.internal.util.ScalaClassLoader.asContext(ScalaClassLoader.scala:36)
	at scala.reflect.internal.util.ScalaClassLoader.asContext$(ScalaClassLoader.scala:116)
	at scala.reflect.internal.util.AbstractFileClassLoader.asContext(AbstractFileClassLoader.scala:41)
	at scala.tools.nsc.interpreter.IMain.loadAndRunReq$1(IMain.scala:567)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:594)
	at scala.tools.nsc.interpreter.IMain.interpret(IMain.scala:564)
	at com.databricks.backend.daemon.driver.DriverILoop.execute(DriverILoop.scala:219)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.$anonfun$repl$1(ScalaDriverLocal.scala:225)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExitInternal$.trapExit(DriverLocal.scala:1003)
	at com.databricks.backend.daemon.driver.DriverLocal$TrapExit$.apply(DriverLocal.scala:956)
	at com.databricks.backend.daemon.driver.ScalaDriverLocal.repl(ScalaDriverLocal.scala:225)
	at com.databricks.backend.daemon.driver.DriverLocal.$anonfun$execute$13(DriverLocal.scala:634)
	at ```
com.databricks.logging.Log4jUsageLoggingShim$.$anonfun$withAttributionContext$1(Log4jUsageLoggingShim.scala:33)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
	at com.databricks.logging.AttributionContext$.withValue(AttributionContext.scala:94)
	at com.databricks.logging.Log4jUsageLoggingShim$.withAttributionContext(Log4jUsageLoggingShim.scala:31)
	at com.databricks.logging.UsageLogging.withAttributionContext(UsageLogging.scala:205)
	at com.databricks.logging.UsageLogging.withAttributionContext$(UsageLogging.scala:204)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionContext(DriverLocal.scala:59)
	at com.databricks.logging.UsageLogging.withAttributionTags(UsageLogging.scala:240)
	at com.databricks.logging.UsageLogging.withAttributionTags$(UsageLogging.scala:225)
	at com.databricks.backend.daemon.driver.DriverLocal.withAttributionTags(DriverLocal.scala:59)
	at com.databricks.backend.daemon.driver.DriverLocal.execute(DriverLocal.scala:611)
	at com.databricks.backend.daemon.driver.DriverWrapper.$anonfun$tryExecutingCommand$1(DriverWrapper.scala:615)
	at scala.util.Try$.apply(Try.scala:213)
	at com.databricks.backend.daemon.driver.DriverWrapper.tryExecutingCommand(DriverWrapper.scala:607)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommandAndGetError(DriverWrapper.scala:526)
	at com.databricks.backend.daemon.driver.DriverWrapper.executeCommand(DriverWrapper.scala:561)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInnerLoop(DriverWrapper.scala:431)
	at com.databricks.backend.daemon.driver.DriverWrapper.runInner(DriverWrapper.scala:374)
	at com.databricks.backend.daemon.driver.DriverWrapper.run(DriverWrapper.scala:225)
	at java.lang.Thread.run(Thread.java:750)
```
```
